[package]
edition = { workspace = true }
name = "wsm-common"
publish.workspace = true
version = "0.1.0"

[dependencies]
base64 = { workspace = true }
bitcoin = { version = "0.30", features = ["serde"] }
crypto = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["base64"] }

[lints]
workspace = true
