services:
  dynamodb:
    image: amazon/dynamodb-local
    healthcheck:
      # to avoid aws-cli dependency, just see if the endpoint returns an unauthenticated error to show it can process
      test: curl -s -o /dev/null -w '%{http_code}' http://localhost:8000/ | grep -q '400'
      interval: 5s
      timeout: 5s
      retries: 10
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - "8000:8000"

  dynamodb-admin:
    links:
      - dynamodb
    image: aaronshaf/dynamodb-admin
    environment:
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY:
      AWS_SECRET_ACCESS_KEY:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    ports:
      - "8001:8001"

  jaeger:
    image: jaegertracing/jaeger:2.1.0
    ports:
      - "4317:4317/tcp"
      - "4318:4318/tcp"
      - "5778:5778/tcp"
      - "9411:9411/tcp"
      - "16686:16686"

  bitcoind:
    extends:
      file: docker-compose-bitcoin.base.yml
      service: bitcoind

volumes:
  bitcoin-data:
